FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Install serve globally
RUN npm install -g serve
EXPOSE 5173

# Use serve to host the production build
CMD ["serve", "-s", "dist", "-l", "5173"]
