services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5173:5173"
    networks:
      - ticketapp-network
    restart: unless-stopped
    

networks:
  ticketapp-network:
    external: true
