services:
  upload-service:
    build: .
    ports:
      - "8091:8091"
    environment:
      - PORT=8091
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=eventimagebucket
    networks:
      - ticketapp-network

networks:
  ticketapp-network:
    external: true