
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: booking-notification-websocket
          uri: lb:ws://booking-notification-service
          predicates:
            - Path=/api/ws-notifications/**
          filters:
            - StripPrefix=1
server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    preferIpAddress: true