spring:
  application:
    name: Event-Service
  datasource:
    url: jdbc:postgresql://postgres:5432/eventdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  elasticsearch:
    rest:
      uris: http://elasticsearch:9200
    
    
  data:
    elasticsearch:
      repositories:
        enabled: true  # Enable Elasticsearch repositories
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    preferIpAddress: true


logging:
  level:
    root: INFO
    com.ticketbooking: WARN
    org.springframework.web: WARN
