services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - ticketapp-network
volumes:
  minio_data:

networks:
  ticketapp-network:
    external: true